M48
; DRILL file {KiCad 9.0.2} date 2025-12-07T17:47:31-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-07T17:47:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.020
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X192.25Y-86.08
X192.25Y-95.08
T2
X218.6Y-37.4
X294.64Y-72.06
X294.64Y-126.56
X296.36Y-37.4
M30
